"""add waitlist_requests table

Revision ID: 27ee92e478ce
Revises: b9f3ce5c9d5f
Create Date: 2026-04-03 13:18:31.763829

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27ee92e478ce"
down_revision: str | Sequence[str] | None = "b9f3ce5c9d5f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "waitlist_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "email",
            sa.String(length=254),
            nullable=False,
            comment="Applicant email — lowercased at write time",
        ),
        sa.Column(
            "status", sa.String(length=20), nullable=False, comment="pending | approved | rejected"
        ),
        sa.Column(
            "email_sent_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the approval email was last sent (NULL = not sent yet)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the request was submitted",
        ),
        sa.Column(
            "approved_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the request was approved",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected')", name="ck_waitlist_requests_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_waitlist_requests_email"), "waitlist_requests", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_waitlist_requests_email"), table_name="waitlist_requests")
    op.drop_table("waitlist_requests")
    # ### end Alembic commands ###
