"""add users table

Revision ID: 2bcc0c92bad5
Revises: de3eafa552b5
Create Date: 2026-03-09 22:35:49.082018

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2bcc0c92bad5"
down_revision: str | Sequence[str] | None = "de3eafa552b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "telegram_id", sa.BigInteger(), nullable=False, comment="Telegram user ID (64-bit)"
        ),
        sa.Column("username", sa.String(), nullable=True, comment="Telegram @handle (may change)"),
        sa.Column("first_name", sa.String(), nullable=False, comment="Telegram first name"),
        sa.Column(
            "role",
            sa.String(length=20),
            nullable=False,
            comment="Authorization role: user or admin",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Active flag (replaces bot allowlist)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When user first registered",
        ),
        sa.Column(
            "last_login_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Last successful login (updated on each auth)",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
