"""add invite code tables

Revision ID: 693a0bde405a
Revises: 63fc43757bbb
Create Date: 2026-03-12 17:15:29.593399

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "693a0bde405a"
down_revision: str | Sequence[str] | None = "63fc43757bbb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="Owner of this chat session"),
        sa.Column(
            "title",
            sa.String(),
            nullable=True,
            comment="Auto-generated from first message (~50 chars)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When session was started",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Last message timestamp",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_sessions_user_id"), "chat_sessions", ["user_id"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False, comment="Parent chat session"),
        sa.Column(
            "role",
            sa.String(length=20),
            nullable=False,
            comment="Message author: user or assistant",
        ),
        sa.Column("content", sa.Text(), nullable=False, comment="Message text content"),
        sa.Column(
            "chat_meta",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Structured payload: intent, product SKUs, log_id, summary",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When message was sent",
        ),
        sa.ForeignKeyConstraint(["session_id"], ["chat_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_messages_session_id"), "chat_messages", ["session_id"], unique=False
    )
    op.alter_column(
        "products",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        comment="Wine semantic embedding (text-embedding-3-large, 1536d)",
        existing_comment="Wine semantic embedding (multilingual-e5-large, 1024d)",
        existing_nullable=True,
    )
    op.alter_column(
        "products",
        "last_embedded_hash",
        existing_type=sa.VARCHAR(),
        comment="Hash of embedding-relevant fields at last embed sync",
        existing_comment="embedding_input_hash at time of last --embed-sync run",
        existing_nullable=True,
    )
    op.drop_column("recommendation_logs", "error")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recommendation_logs",
        sa.Column(
            "error",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="Error type if pipeline failed",
        ),
    )
    op.alter_column(
        "products",
        "last_embedded_hash",
        existing_type=sa.VARCHAR(),
        comment="embedding_input_hash at time of last --embed-sync run",
        existing_comment="Hash of embedding-relevant fields at last embed sync",
        existing_nullable=True,
    )
    op.alter_column(
        "products",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        comment="Wine semantic embedding (multilingual-e5-large, 1024d)",
        existing_comment="Wine semantic embedding (text-embedding-3-large, 1536d)",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_chat_messages_session_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_chat_sessions_user_id"), table_name="chat_sessions")
    op.drop_table("chat_sessions")
    # ### end Alembic commands ###
