"""add cellar_entries table

Revision ID: a321897f6ef7
Revises: d54ff3a506b5
Create Date: 2026-08-05 00:15:23.408637

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a321897f6ef7"
down_revision: str | Sequence[str] | None = "d54ff3a506b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cellar_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="Owning user"),
        sa.Column("sku", sa.String(), nullable=False, comment="Cellared product SKU"),
        sa.Column("quantity", sa.Integer(), nullable=False, comment="Bottles owned"),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When this entry was added",
        ),
        sa.CheckConstraint("quantity > 0", name="ck_cellar_entries_quantity"),
        sa.ForeignKeyConstraint(
            ["sku"],
            ["products.sku"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "sku", name="uq_cellar_entries_user_sku"),
    )
    op.create_index(op.f("ix_cellar_entries_sku"), "cellar_entries", ["sku"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cellar_entries_sku"), table_name="cellar_entries")
    op.drop_table("cellar_entries")
    # ### end Alembic commands ###
