"""add tasting_notes table

Revision ID: b9f3ce5c9d5f
Revises: 5ee06183fa43
Create Date: 2026-04-01 17:12:23.229960

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9f3ce5c9d5f"
down_revision: str | Sequence[str] | None = "5ee06183fa43"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasting_notes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.String(),
            nullable=False,
            comment="Channel-prefixed user ID (e.g. tg:123456)",
        ),
        sa.Column("sku", sa.String(), nullable=False, comment="Tasted product SKU"),
        sa.Column("rating", sa.Integer(), nullable=False, comment="Parker-style rating 0-100"),
        sa.Column("notes", sa.Text(), nullable=True, comment="Free-text tasting notes"),
        sa.Column("pairing", sa.Text(), nullable=True, comment="Free-text food pairing"),
        sa.Column("tasted_at", sa.Date(), nullable=False, comment="Date the wine was tasted"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When note was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When note was last updated",
        ),
        sa.ForeignKeyConstraint(["sku"], ["products.sku"]),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("rating >= 0 AND rating <= 100", name="ck_tasting_notes_rating"),
    )
    op.create_index(op.f("ix_tasting_notes_sku"), "tasting_notes", ["sku"], unique=False)
    op.create_index(op.f("ix_tasting_notes_user_id"), "tasting_notes", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasting_notes_user_id"), table_name="tasting_notes")
    op.drop_index(op.f("ix_tasting_notes_sku"), table_name="tasting_notes")
    op.drop_table("tasting_notes")
    # ### end Alembic commands ###
